added local minio s3 and backup:mongodb script
asuc-octo/berkeleytime pull request #649
Opened 2023-11-02 01:16 UTC by ARtheboss

2023-11-07 01:03 UTC, kevinzwang requested changes
Looking good. I'd also like to see a restore script (with parameters for the collections to restore) so we can test this end-to-end before merge

2023-11-07 01:03 UTC, kevinzwang commented on backend/src/config.ts
> +  S3_MONGO_BACKUP_BUCKET: env("S3_MONGO_BACKUP_BUCKET"),
maybe put these under an s3 key like `config.mongoDB`

2023-11-07 01:03 UTC, kevinzwang commented on backend/src/scripts/backup-mongodb.ts
> +    const client = new Minio.Client({
is this compatible with any S3 service? we are only using minio for local testing

2023-11-09 22:01 UTC, ARtheboss commented
@kevinzwang added your requested changes

2024-02-21 22:52 UTC, ARtheboss commented
@kevinzwang should be good to go

2024-02-23 03:01 UTC, kevinzwang approved these changes
LGTM. Resolve your conflicts and then pls squash and merge!

2024-03-06 22:37 UTC, merged